//LOGIN
export const ADD_LOGIN = "ADD_LOGIN";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const REMOVE_LOGIN = "REMOVE_LOGIN";

//Sign up
export const ADD_SIGNUP = "ADD_SIGNUP";
export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const REMOVE_SIGNUP = "REMOVE_SIGNUP";

// Customer actionTypes

export const CUSTOMER_GET_DATA = "CUSTOMER_GET_DATA";
export const CUSTOMER_SET_DATA = "CUSTOMER_SET_DATA";
export const CUSTOMER_FAIL_DATA = "CUSTOMER_FAIL_DATA";
export const DELETE_CUSTOMER_FAIL = "DELETE_CUSTOMER_FAIL";
export const POST_CUSTOMER_DATA = "POST_CUSTOMER_DATA";
export const POST_CUSTOMER_DATA_START = "POST_CUSTOMER_DATA_START";
export const POST_CUSTOMER_DATA_FAIL = "POST_CUSTOMER_DATA_FAIL";
export const POST_CUSTOMER_DATA_SUCCESS = "POST_CUSTOMER_DATA_SUCCESS";
export const EDIT_CUSTOMER_ROW_START = "EDIT_CUSTOMER_ROW_START";

export const FAIL_EDIT_CUSTOMER = "FAIL_EDIT_CUSTOMER";
export const CURRENT_USER_EDIT_CUSTOMER = "CURRENT_USER_EDIT_CUSTOMER";
export const UPDATE_CUSTOMER_DATA_START = "UPDATE_CUSTOMER_DATA_START";

// Franchisor actionTypes

export const FRANCHISOR_GET_DATA = "FRANCHISOR_GET_DATA";
export const FRANCHISOR_SET_DATA = "FRANCHISOR_SET_DATA";
export const FRANCHISOR_FAIL_DATA = "FRANCHISOR_FAIL_DATA";
export const DELETE_FRANCHISOR_FAIL = "DELETE_FRANCHISOR_FAIL";
export const POST_FRANCHISOR_DATA = "POST_FRANCHISOR_DATA";
export const POST_FRANCHISOR_DATA_START = "POST_FRANCHISOR_DATA_START";
export const POST_FRANCHISOR_DATA_FAIL = "POST_FRANCHISOR_DATA_FAIL";
export const POST_FRANCHISOR_DATA_SUCCESS = "POST_FRANCHISOR_DATA_SUCCESS";
export const EDIT_FRANCHISOR_ROW_START = "EDIT_FRANCHISOR_ROW_START";

export const FAIL_EDIT_FRANCHISOR = "FAIL_EDIT_FRANCHISOR";
export const CURRENT_USER_EDIT_FRANCHISOR = "CURRENT_USER_EDIT_FRANCHISOR";
export const UPDATE_FRANCHISOR_DATA_START = "UPDATE_FRANCHISOR_DATA_START";

// Franchise actionTypes

export const FRANCHISE_GET_DATA = "FRANCHISE_GET_DATA";
export const FRANCHISE_SET_DATA = "FRANCHISE_SET_DATA";
export const FRANCHISE_FAIL_DATA = "FRANCHISE_FAIL_DATA";
export const DELETE_FRANCHISE_FAIL = "DELETE_FRANCHISE_FAIL";
export const POST_FRANCHISE_DATA = "POST_FRANCHISE_DATA";
export const POST_FRANCHISE_DATA_START = "POST_FRANCHISE_DATA_START";
export const POST_FRANCHISE_DATA_FAIL = "POST_FRANCHISE_DATA_FAIL";
export const POST_FRANCHISE_DATA_SUCCESS = "POST_FRANCHISE_DATA_SUCCESS";
export const EDIT_FRANCHISE_ROW_START = "EDIT_FRANCHISE_ROW_START";

export const FAIL_EDIT_FRANCHISE = "FAIL_EDIT_FRANCHISE";
export const CURRENT_USER_EDIT_FRANCHISE = "CURRENT_USER_EDIT_FRANCHISE";
export const UPDATE_FRANCHISE_DATA_START = "UPDATE_FRANCHISE_DATA_START";

// Franchise actionTypes

export const OFFER_GET_DATA = "OFFER_GET_DATA";
export const OFFER_SET_DATA = "OFFER_SET_DATA";
export const OFFER_FAIL_DATA = "OFFER_FAIL_DATA";
export const DELETE_OFFER_FAIL = "DELETE_OFFER_FAIL";
export const POST_OFFER_DATA = "POST_OFFER_DATA";
export const POST_OFFER_DATA_START = "POST_OFFER_DATA_START";
export const POST_OFFER_DATA_FAIL = "POST_OFFER_DATA_FAIL";
export const POST_OFFER_DATA_SUCCESS = "POST_OFFER_DATA_SUCCESS";
export const EDIT_OFFER_ROW_START = "EDIT_OFFER_ROW_START";

export const FAIL_EDIT_OFFER = "FAIL_EDIT_OFFER";
export const CURRENT_USER_EDIT_OFFER = "CURRENT_USER_EDIT_OFFER";
export const UPDATE_OFFER_DATA_START = "UPDATE_OFFER_DATA_START";

// Lead actionTypes

export const LEAD_GET_DATA = "LEAD_GET_DATA";
export const LEAD_SET_DATA = "LEAD_SET_DATA";
export const LEAD_FAIL_DATA = "LEAD_FAIL_DATA";
export const DELETE_LEAD_FAIL = "DELETE_LEAD_FAIL";
export const POST_LEAD_DATA = "POST_LEAD_DATA";
export const POST_LEAD_DATA_START = "POST_LEAD_DATA_START";
export const POST_LEAD_DATA_FAIL = "POST_LEAD_DATA_FAIL";
export const POST_LEAD_DATA_SUCCESS = "POST_LEAD_DATA_SUCCESS";
export const EDIT_LEAD_ROW_START = "EDIT_LEAD_ROW_START";

export const FAIL_EDIT_LEAD = "FAIL_EDIT_LEAD";
export const CURRENT_USER_EDIT_LEAD = "CURRENT_USER_EDIT_LEAD";
export const UPDATE_LEAD_DATA_START = "UPDATE_LEAD_DATA_START";

// Slide actionTypes

export const SLIDE_GET_DATA = "SLIDE_GET_DATA";
export const SLIDE_SET_DATA = "SLIDE_SET_DATA";
export const SLIDE_FAIL_DATA = "SLIDE_FAIL_DATA";
export const DELETE_SLIDE_FAIL = "DELETE_SLIDE_FAIL";
export const POST_SLIDE_DATA = "POST_SLIDE_DATA";
export const POST_SLIDE_DATA_START = "POST_SLIDE_DATA_START";
export const POST_SLIDE_DATA_FAIL = "POST_SLIDE_DATA_FAIL";
export const POST_SLIDE_DATA_SUCCESS = "POST_SLIDE_DATA_SUCCESS";
export const EDIT_SLIDE_ROW_START = "EDIT_SLIDE_ROW_START";

export const FAIL_EDIT_SLIDE = "FAIL_EDIT_SLIDE";
export const CURRENT_USER_EDIT_SLIDE = "CURRENT_USER_EDIT_SLIDE";
export const UPDATE_SLIDE_DATA_START = "UPDATE_SLIDE_DATA_START";

// Contact actionTypes

export const CONTACT_GET_DATA = "CONTACT_GET_DATA";
export const CONTACT_SET_DATA = "CONTACT_SET_DATA";
export const CONTACT_FAIL_DATA = "CONTACT_FAIL_DATA";
export const DELETE_CONTACT_FAIL = "DELETE_CONTACT_FAIL";
export const POST_CONTACT_DATA = "POST_CONTACT_DATA";
export const POST_CONTACT_DATA_START = "POST_CONTACT_DATA_START";
export const POST_CONTACT_DATA_FAIL = "POST_CONTACT_DATA_FAIL";
export const POST_CONTACT_DATA_SUCCESS = "POST_CONTACT_DATA_SUCCESS";
export const EDIT_CONTACT_ROW_START = "EDIT_CONTACT_ROW_START";

export const FAIL_EDIT_CONTACT = "FAIL_EDIT_CONTACT";
export const CURRENT_USER_EDIT_CONTACT = "CURRENT_USER_EDIT_CONTACT";
export const UPDATE_CONTACT_DATA_START = "UPDATE_CONTACT_DATA_START";
